fix(Button): change disabled style
TicketSwap/solar pull request #438
Opened 2019-11-13 14:40 UTC by luciatoma

# Description

Improve style for `disabled` button state.
[JIRA task](https://ticketswap.atlassian.net/browse/TTN-1791)

### How to test

- Checkout this branch
- run `yarn`
- Check `disabled` states for `Button` component

2019-11-13 16:32 UTC, rppld commented
We can basically remove all the specific `disabled` style declarations for the different variants if we move forward with this change. The only one that needs to stay is

```jsx
${props =>
    props.disabled &&
    css`
      opacity: 0.35;
      text-shadow: none;
    `};
```

2019-11-13 16:32 UTC, rppld requested changes
We can basically remove all the specific `disabled` style declarations for the different variants if we move forward with this change. The only one that needs to stay is

```jsx
${props =>
    props.disabled &&
    css`
      opacity: 0.35;
      text-shadow: none;
    `};
```

2019-11-14 09:14 UTC, luciatoma commented
> We can basically remove all the specific `disabled` style declarations for the different variants if we move forward with this change. The only one that needs to stay is
> 
> ```js-jsx
> ${props =>
>     props.disabled &&
>     css`
>       opacity: 0.35;
>       text-shadow: none;
>     `};
> ```

I updated the PR, but left the styling defined for `hover` state (as we want to keep the same background when hovering on a disabled button) 👍

2019-11-14 09:42 UTC, rppld commented on src/components/Button/index.js
> +      text-shadow: none;
I think the text-shadow can stay for disabled buttons.

2019-11-14 09:43 UTC, rppld commented on src/components/Button/index.js
> +      opacity: 0.35;
I’ll have a look at this with @jelleoverbeek at the office, we might increase this a bit to `0.5`.

2019-11-14 15:45 UTC, rppld approved these changes

2019-11-14 15:46 UTC, merged

2019-11-14 15:48 UTC, lucasfeliciano commented
:tada: This PR is included in version 8.3.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ticketswap/solar)
- [GitHub release](https://github.com/TicketSwap/solar/releases/tag/v8.3.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: